FROM gcr.io/dulcet-nucleus-331721/x86/tf-base:latest

# Simple root password in case we want to customize the container
# RUN echo "root:root" | chpasswd
# RUN useradd -G video -ms /bin/bash user


#COPY assets/ /assets

USER user
WORKDIR /qt

CMD ["bash"]
